dev:
  image: kino/sps
  hostname: dev.localdomain
  privileged: true
  dns:
    - 8.8.8.8
  dns_search:
    - localdomain
  ports:
    - "127.0.0.1:4222:22"
  volumes:
    - /usr/local/docker:/usr/local/docker-host

devcopy:
  image: kino/sps
  hostname: devcopy.localdomain
  volumes:
    - /usr/local/docker:/usr/local/docker-host
  command: /usr/local/copy.sh

shairplay-sync:
  extends:
    service: devcopy
  image: kino/sps
